Lab2/Models/Birth.cs
namespace Lab2.Models
{
    public class Birth
    {
        public string? Name { get; set; }
        public DateTime BirthDate { get; set; }


        public bool IsValid()
        {
            return Name != null && BirthDate < DateTime.Now;
        }

        public int Age()
        {
            return DateTime.Today.Year - BirthDate.Year;
        }
    }
}

Lab2/Models/Calculator.cs
using Lab2.Controllers;

namespace Lab2.Models
{
    public class Calculator
    {
        public Operators? Operator { get; set; }
        public double? X { get; set; }
        public double? Y { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case Operators.ADD:
                        return "+";
                    case Operators.SUB:
                        return "-";
                    case Operators.MUL:
                        return "*";
                    case Operators.DIV:
                        return "/";
                    default:
                        return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && X != null && Y != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.ADD:
                    return (double)(X + Y);
                case Operators.SUB:
                    return (double)(X - Y);
                case Operators.MUL:
                    return (double)(X * Y);
                case Operators.DIV:
                    return (double)(X / Y);
                default: return double.NaN;
            }
        }
    }
}

Lab2/Models/ErrorViewModel.cs
namespace Lab2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab2/Controllers/BirthController.cs
using Lab2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab2.Controllers
{
    public class BirthController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm] Birth model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
    }
}

Lab2/Controllers/CalculatorController.cs
using Lab2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab2.Controllers
{
    public enum Operators
    {
        ADD, SUB, MUL, DIV
    }
    public class CalculatorController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result([FromForm] Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }

        //public IActionResult Result([FromQuery(Name = "operator")] Operators? op, double? x, double? y)
        //{
        //    if (x == null || y == null)
        //    {
        //        return View("Error");
        //    };
        //    switch (op)
        //    {
        //        case Operators.ADD:
        //            ViewBag.result = x + y;
        //            break;
        //        case Operators.SUB:
        //            ViewBag.result = x - y;
        //            break;
        //        case Operators.MUL:
        //            ViewBag.result = x * y;
        //            break;
        //        case Operators.DIV:
        //            ViewBag.result = x / y;
        //            break;
        //        default:
        //            return View("Error");
        //    }

        //    double? result = x + y;
        //    ViewBag.result = result;
        //    return View();
        //}
    }
}

Lab2/Controllers/HomeController.cs
using Lab2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab2/Views/Birth/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>BirthCheck</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="name">Imię</label>
                    <input class="form-control" type="text" name="name" id="name" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="birthDate">Data urodzenia</label>
                    <input class="form-control" type="date" name="birthDate" id="birthDate" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

Lab2/Views/Birth/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>Cześć @Model.Name, masz <b class="text-danger">@Model.Age()</b> lat(a).</H3>

Lab2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="x" step="0.00001" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select class="form-control" name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="y" step="0.00001" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

Lab2/Views/Calculator/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y = <b class="text-danger">@Model.Calculate()</b></H3>

Lab2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Calculator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Form">Date of birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lab2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>